### PR TITLE
#2 fixed 

### LINKED ISSUE #2: Improve styles.css file to make the UI look as its intented
Create the CSS file (styles.css) to style the web application as shown in the [Final version of the Product](https://github.com/gdsc-jssstu/CipherBox#final-version-of-the-project) section.

### PR DESCRIPTION
**Pull request by rajvinder-kaur**
fixes #2 #3 
worked on the given ui and tried my best to make it similar to intended ui and added responsive design to the layout 

ss

### CODE REVIEW

**Comment by theinit01** [comment]
Looks good but need some improvements.
will be merging this but can you please make it more refined

**Comment by rajvinder-kaur** [comment]
can u please tell me the refinements you want

**Comment by rajvinder-kaur** [comment]
i made some changes , can u please review

**Comment by theinit01** [comment]
Can you please provide a screenshot for the result?

**Comment by rajvinder-kaur** [comment]
image

**Pull request merged**
